### ISSUE TITLE
GitHub Blog URLs incorrectly redirecting

### ISSUE THREAD

**Issue by jfelchner** [hbang/libopener#10]
Not sure if this is the proper repo but there are a couple issues I've run into. I'll put the min separate issues.

Github's blog URLs redirect to ioctocat and they should not. 

https://github.com/blog

**Comment by kirb** [comment]
Can you please file this at [hbang/LinkOpener](https://github.com/hbang/LinkOpener) along with your other issue? Will continue it there.
