### ISSUE TITLE
Preference Pane Crashing on iOS 5.1.1

### ISSUE THREAD

**Issue by minimum91** [hbang/libopener#14]
Gets a little confusing when I read that this supports iOS 6 and up, yet the changelog states fixes crashing I've been experiencing on iOS 5. So I thought I'd install and see. Still crashing. How can I provide any useful help (logs, etc.)?

**Comment by iAdam1n** [comment]
Install Crash Reporter and then [follow this](http://www.idownloadblog.com/2015/01/13/troubleshoot-jailbreak-tweak-crashes-crashreporter/) to email us the crash log to support@hbang.ws.

**Comment by kirb** [comment]
Don’t think we got an email, so closing this. I think this would be regarding some iOS 5/6 crashes we fixed in Cephei 1.11 or so.
