### ISSUE TITLE
libopener does not install on iphone 5,4 ios 10.3.3

### ISSUE THREAD

**Issue by tiuno** [hbang/libopener#15]
I have jailbroken my iPhone 5,4 (iPhone 5c) runing iOS 10.3.3 with h3lix.  Previously, when the phone was running iOS 8 libopener and MapsOpener would install and work fine. Now, libopener cannot be installed through the package Opener using Cydia. Cydia reports that the dependency iOS Firmware < 10.3 is not met.  Is it possible to update the package or is libopener not compatible with iOS 10.3 for more complicated reasons?

**Comment by kirb** [comment]
iOS 10.3 had some pretty major changes that broke Opener. I'm working on it.

**Comment by kirb** [comment]
3.1.3 will be out soonish with iOS 10.3 + 11 support.
