### ISSUE TITLE
Depends iOS Firmware < 11.3

### ISSUE THREAD

**Issue by nathancahill** [hbang/libopener#18]
Is this a real limitation of 11.3 or can this version be bumped up?

**Comment by kirb** [comment]
I’d be certain it works on 11.4, just haven’t tested it personally.

If you know how to unpack and repack a deb, you can try changing `firmware (<< 11.4)` inside `DEBIAN/control` to `firmware (<< 12.0)` and let me know if it works.

**Comment by nathancahill** [comment]
It looks like the version on the hbang repo has `<< 11.4`. The version on BigBoss has `<< 11.3`. Once it's installed from hbang, BrowserChanger 10 can be installed, but doesn't work. Not sure if an issue with BrowserChanger 10 or libopener.

**Comment by nathancahill** [comment]
Hmm, yeah it seems that none of the Openers work on 11.3 with 3.2.2.

**Comment by nathancahill** [comment]
Here's the relevant logs: https://gist.githubusercontent.com/nathancahill/d4a39139c26969d3a7ba07921a75e7de/raw/f57be682b2639488b40b34632490b14ae8ed4e24/errors.log

**Comment by nathancahill** [comment]
A workaround from @Jakeashacks for loading dylibs with mmap:

```c
uint64_t getVnodeAtPath(uint64_t vfs_context, const char *path) {
    uint64_t *vnode_ptr = (uint64_t *)malloc(8);
    if (vnode_lookup(path, 0, vnode_ptr, vfs_context)) {
        printf("unable to get vnode from path for %s\n", path);
        return -1;
    }
    else {
        uint64_t vnode = *vnode_ptr;
        free(vnode_ptr);
        return vnode;
    }
}
```

```c
int fixupdylib(char *dylib) {
    #define VSHARED_DYLD 0x000200

    uint64_t vnode = getVnodeAtPath(dylib); // get vnode
    if (!vnode) {
        return -1;
    }
    uint32_t v_flags = KernelRead_32bits(vnode + offsetof_v_flags); // 0x54
    if (v_flags & VSHARED_DYLD) return 0; // check if there already

    KernelWrite_32bits(vnode + offsetof_v_flags, v_flags | VSHARED_DYLD); // add

    v_flags = KernelRead_32bits(vnode + offsetof_v_flags);
    vnode_put(vnode);
    return !(v_flags & VSHARED_DYLD);
}

```

**Comment by kirb** [comment]
There was actually an issue with the stashing script (`move.sh`) included with Cydia, which Opener calls on installation. It’s meant to be essentially a no-op on iOS 11 and newer since it’s no longer needed, and binaries can’t be loaded from /var anyway (without a hack like you posted). @sbingner has just fixed it with an update to Cydia, but since you’ve already invoked the older version of the script, you’ll need to uninstall Opener and reinstall. (You could also move the stashed dir manually to /usr/lib/Opener, overwriting the symlink.)

Thanks for filing this issue!

**Comment by nathancahill** [comment]
I'm not sure this is fixed. I'm getting the same `deny()` errors after reinstalling Cydia and then reinstalling Opener.

**Comment by nathancahill** [comment]
Overwriting the symlink does work though.

**Comment by kirb** [comment]
Oops, I think the symlink isn’t deleted with an uninstall. I need to think of a safe automated workaround for people who already installed on unc0ver…

**Comment by sbingner** [comment]
preeinst if -L should do it for you?
