### ISSUE TITLE
Localize to languages supported by iOS

### ISSUE THREAD

**Issue by iAdam1n** [hbang/libopener#3]
- [x] Arabic `ar.lproj`
- [x] Catalan `ca.lproj`
- [x] Chinese (Hong Kong) `zh_HK.lproj`
- [x] Chinese (Simplified) `zh_CN.lproj`
- [x] Chinese (Traditional) `zh_TW.lproj`
- [x] Croatian `hr.lproj`
- [x] Czech `cs.lproj`
- [x] Danish `da.lproj`
- [x] Dutch `nl.lproj`
- [x] English `en.lproj`
- [x] English (Australian) `en_AU.lproj`
- [x] English (British) `en_GB.lproj`
- [x] Finnish `fi.lproj`
- [x] French `fr.lproj`
- [x] French (Canadian) `fr_CA.lproj`
- [x] German `de.lproj`
- [x] Greek `el.lproj`
- [x] Hebrew `he.lproj`
- [x] Hindi `hi.lproj`
- [x] Hungarian `hu.lproj`
- [x] Indonesian `id.lproj`
- [x] Italian `it.lproj`
- [x] Japanese `ja.lproj`
- [x] Korean `ko.lproj`
- [x] Malay `ms.lproj`
- [x] Norwegian (Bokmål) `nb.lproj`
- [x] Polish `pl.lproj`
- [x] Portuguese `pt.lproj`
- [x] Portuguese (Portugal) `pt_PT.lproj`
- [x] Romanian `ro.lproj`
- [x] Russian `ru.lproj`
- [x] Slovak `sk.lproj`
- [x] Spanish `es.lproj`
- [x] Spanish (Mexico) `es_MX.lproj`
- [x] Swedish `sv.lproj`
- [x] Thai `th.lproj`
- [x] Turkish `tr.lproj`
- [x] Ukrainian `uk.lproj`
- [x] Vietnamese `vi.lproj`

**Comment by Bananastudios** [comment]
Arabic ar.lproj
 Catalan ca.lproj
 Chinese (Hong Kong) zh_HK.lproj
 Chinese (Simplified) zh_CN.lproj
 Chinese (Traditional) zh_TW.lproj
 Croatian hr.lproj
 Czech cs.lproj
 Danish da.lproj
 Dutch nl.lproj
 English en.lproj
 English (Australian) en_AU.lproj
 English (British) en_GB.lproj
 Finnish fi.lproj
 French fr.lproj
 French (Canadian) fr_CA.lproj
 German de.lproj
 Greek el.lproj
 Hebrew he.lproj
 Hindi hi.lproj
 Hungarian hu.lproj
 Indonesian id.lproj
 Italian it.lproj
 Japanese ja.lproj
 Korean ko.lproj
 Malay ms.lproj
 Norwegian (Bokmål) nb.lproj
 Polish pl.lproj
 Portuguese pt.lproj
 Portuguese (Portugal) pt_PT.lproj
 Romanian ro.lproj
 Russian ru.lproj
 Slovak sk.lproj
 Spanish es.lproj
 Spanish (Mexico) es_MX.lproj
 Swedish sv.lproj
 Thai th.lproj
 Turkish tr.lproj
 Ukrainian uk.lproj
 Vietnamese vi.lproj

**Comment by meetdesai** [comment]
hey i got the hindi strings where do i upload it?

**Comment by meetdesai** [comment]
https://www.dropbox.com/sh/tapnychhowqbugs/AAA9f-BTSMEchM8hNM-exLHua?dl=0 thats hindi
