### ISSUE TITLE
Tapping a notification from NC clears it rather than opening app

### ISSUE THREAD

**Issue by iAdam1n** [hbang/libopener#6]
Syslog - https://ghostbin.com/paste/ymfno

**Comment by CoBrA2168** [comment]
Wanted to chime in and say that I'm experiencing this issue with notifications from Apple's Message app.  Would be willing to help debug if it would prove to be useful.

**Comment by iAdam1n** [comment]
Thanks however we have that covered since we can reproduce but will bare it in mind.

**Comment by iAdam1n** [comment]
Fixed in 3.0.1.
